import pyautogui
import time
import autopy

def com1():
    time.sleep(2)
    pyautogui.keyDown('d')
    pyautogui.keyDown('w')
    pyautogui.keyUp('d')
    pyautogui.keyUp('w')
    time.sleep(0.15)
    pyautogui.keyDown('num9')
    pyautogui.keyUp('num9')
    time.sleep(0.4)
    pyautogui.keyDown('num6')
    time.sleep(0.03)
    pyautogui.keyDown('s')
    pyautogui.keyDown('d')
    pyautogui.keyUp('num6')
    pyautogui.keyUp('s')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('d')
    pyautogui.keyUp('num8')

    print('com1')
def com2():
    time.sleep(2)
    pyautogui.keyDown('d')
    time.sleep(0.2)
    pyautogui.keyUp('d')
    time.sleep(0.2)
    pyautogui.keyDown('w')
    pyautogui.keyUp('w')
    time.sleep(0.3)
    pyautogui.keyDown('num9')
    pyautogui.keyUp('num9')
    time.sleep(0.4)
    pyautogui.keyDown('num6')
    pyautogui.keyUp('num6')
    pyautogui.keyDown('s')
    time.sleep(0.15)
    pyautogui.keyDown('num5')
    pyautogui.keyUp('s')
    pyautogui.keyUp('num5')
    print('com2')
def com3():
    time.sleep(2)
    pyautogui.keyDown('d')
    time.sleep(0.2)
    pyautogui.keyUp('d')
    time.sleep(0.2)
    pyautogui.keyDown('w')
    pyautogui.keyUp('w')
    time.sleep(0.3)
    pyautogui.keyDown('num9')
    pyautogui.keyUp('num9')
    time.sleep(0.4)
    pyautogui.keyDown('num6')
    pyautogui.keyUp('num6')
    pyautogui.keyDown('s')
    time.sleep(0.15)
    pyautogui.keyDown('num5')
    pyautogui.keyUp('s')
    pyautogui.keyUp('num5')

com1()
com2()
