import pyautogui
import time
import autopy

def jump2shoulder():
    time.sleep(2)
    pyautogui.keyDown('d')
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    pyautogui.keyUp('d')
    pyautogui.keyUp('w')
    time.sleep(0.05)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.35)
    pyautogui.keyDown('num6')
    pyautogui.keyUp('num6')
    time.sleep(0.03)
    pyautogui.keyDown('d')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('d')
    pyautogui.keyUp('num8')
    pyautogui.keyUp('a')
    print('jump2shoulder')

def uppercut():
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(0.2)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.15)
    pyautogui.keyDown('w')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('num8')
    pyautogui.keyUp('w')
    pyautogui.keyUp('s')
    print('uppercut')

def jump2head():
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(0.2)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.15)
    pyautogui.keyDown('w')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('num8')
    pyautogui.keyUp('w')
    pyautogui.keyUp('s')
    print('jump2head')
# uppaercut()
# jump2shoulder()
