import pyautogui
import time
import autopy

def jump2shoulder():
    time.sleep(2)
    pyautogui.keyDown('d')
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    pyautogui.keyUp('d')
    pyautogui.keyUp('w')
    time.sleep(0.05)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.35)
    pyautogui.keyDown('num6')
    pyautogui.keyUp('num6')
    time.sleep(0.03)
    pyautogui.keyDown('d')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('d')
    pyautogui.keyUp('num8')
    pyautogui.keyUp('a')
    print('jump2shoulder')

def uppercut():
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(0.2)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.15)
    pyautogui.keyDown('w')
    pyautogui.keyDown('num8')
    pyautogui.keyUp('num8')
    pyautogui.keyUp('w')
    pyautogui.keyUp('s')
    print('uppercut')

def jump2head():
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(0.1)
    pyautogui.keyDown('w')
    pyautogui.keyUp('w')
    time.sleep(0.3)
    pyautogui.keyDown('num9')
    pyautogui.keyUp('num9')
    time.sleep(0.4)
    pyautogui.keyDown('num6')
    pyautogui.keyUp('num6')
    pyautogui.keyDown('w')
    pyautogui.keyDown('num5')
    pyautogui.keyUp('s')
    pyautogui.keyUp('num5')
    pyautogui.keyUp('w')
    print('jump2head')


def launch2orb():
    time.sleep(2)
    pyautogui.keyDown('s')
    time.sleep(0.2)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    time.sleep(0.15)
    pyautogui.keyDown('d')
    pyautogui.keyUp('s')
    pyautogui.keyDown('num7')
    time.sleep(0.35)
    pyautogui.keyUp('num7')
    pyautogui.keyUp('d')
    time.sleep(0.35)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    print('launch2orb')

def counter2ex():
    time.sleep(2)
    pyautogui.keyDown('num7')
    pyautogui.keyUp('num7')
    pyautogui.keyDown('s')
    time.sleep(0.48)
    pyautogui.keyDown('w')
    pyautogui.keyDown('num1')
    pyautogui.keyDown('a')
    pyautogui.keyUp('w')
    pyautogui.keyUp('s')
    pyautogui.keyUp('num1')
    time.sleep(0.3)
    pyautogui.keyDown('d')
    pyautogui.keyDown('num3')
    pyautogui.keyUp('d')
    pyautogui.keyUp('num3')
    pyautogui.keyUp('a')
    print('counter2ex')

counter2ex()
# launch2orb()
# jump2head()
# uppaercut()
# jump2shoulder()
